[tools]

go = "1.25.7"
nodejs = '24'
python = '3.14.2'
rust = '1.93.0'
terraform = "1.14.4"
kubectl = '1.35.0'
minikube = "latest"
helm = "latest"
helmfile = "latest"
flux2 = "latest"
k9s = "latest"
"github:siderolabs/talos"= { version = "1.12.2", bin = "talosctl", asset_pattern = "talosctl-darwin-arm64" }
"github:budimanjojo/talhelper" = { version = "3.1.3", bin = "talhelper" }
"github:score-spec/score-compose" = "latest"
"github:score-spec/score-k8s" = "latest"
node = "25"
cmake = "latest"
opencode = "latest"
yq = "latest"
jq = "latest"
atuin = "latest"
neovim = "latest"
sops = "latest"
gh = "latest"
act = "latest"
opentofu = "latest"
restic = "latest"
age = "latest"

