[tools]

go = "1.25.6"
nodejs = '24'
python = '3.14.2'
rust = '1.92.0'
terraform = "1.14.4"
kubectl = '1.35.0'
"github:siderolabs/talos"= { version = "1.12.1", bin = "talosctl", asset_pattern = "talosctl-darwin-arm64" }
"github:budimanjojo/talhelper" = { version = "3.1.2", bin = "talhelper" }
"github:score-spec/score-compose" = "latest"
node = "25"
opencode = "latest"
