[tools]

go = "1.25.5"
nodejs = '24'
python = '3.14.2'
rust = '1.92.0'
terraform = "1.14.3"
kubectl = '1.35.0'
"ubi:siderolabs/talos"= { version = "1.11", exe = "talosctl" }
"ubi:budimanjojo/talhelper" = '3.0'
node = "25"
