[tools]

go = "1.25.5"
nodejs = '24'
python = '3.14.2'
rust = '1.91.1'
terraform = "1.14.2"
kubectl = '1.34.3'
"ubi:siderolabs/talos"= { version = "1.11", exe = "talosctl" }
"ubi:budimanjojo/talhelper" = '3.0'
node = "25"
